version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install jq for JSON parsing (optional)
      - apt-get update && apt-get install -y jq

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - pwd && ls -l  # Debugging: Show current dir structure
      
      # Modern AWS CLI login (deprecates --no-include-email)
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
      
      # Set variables
      - REPOSITORY_URI=187393211305.dkr.ecr.us-east-1.amazonaws.com/demowebcontainer
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}  # Fix: Use :- instead of := for default value

  build:
    commands:
      # Only login to Docker Hub if you need to pull FROM Docker Hub images
      - echo "$DOCKERHUB_TOKEN" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      
      # Build with cache and fail fast
      - docker build --pull -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images..."
      
      # Push both tags
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # Optional: Cleanup
      - docker logout  # Log out from Docker Hub
      - docker logout $REPOSITORY_URI  # Log out from ECR